const state = {
  Active: { },
  ActiveList: [],
  ActiveItem: {},
  BodyPart: { },
  BodyPartList: [],
  BodyPartItem: {},
  BodyPartType: { },
  BodyPartTypeList: [],
  BodyPartTypeItem: {},
  Dates: { },
  DatesList: [],
  DatesItem: {},
  MeasurementType: { },
  MeasurementTypeList: [],
  MeasurementTypeItem: {},
  MeasurementTypeCategory: { },
  MeasurementTypeCategoryList: [],
  MeasurementTypeCategoryItem: {},
  Time: { },
  TimeList: [],
  TimeItem: {},
  Unit: { },
  UnitList: [],
  UnitItem: {},
  UnitType: { },
  UnitTypeList: [],
  UnitTypeItem: {},
  Flags: {}
}

export default state
