CREATE TYPE [Stats].[tvp_DailyMeasurement] AS TABLE (
    [Active]                   SMALLINT           NULL,
    [BellyButtonCircumference] DECIMAL (10, 6)    NULL,
    [BicepCircumference]       DECIMAL (10, 6)    NULL,
    [BodyFatPercentage]        DECIMAL (10, 6)    NULL,
    [BonePercentage]           DECIMAL (10, 6)    NULL,
    [CalvesCircumference]      DECIMAL (10, 6)    NULL,
    [ChestCircumference]       DECIMAL (10, 6)    NULL,
    [CreatedAt]                DATETIMEOFFSET (7) NULL,
    [DailyMeasurementID]       INT                NULL,
    [Deleted]                  BIT                NULL,
    [HipCircumference]         DECIMAL (10, 6)    NULL,
    [ID]                       VARCHAR (38)       NULL,
    [MeasurementDate]          DATETIME           NULL,
    [MusclePercentage]         DECIMAL (10, 6)    NULL,
    [NeckCircumference]        DECIMAL (10, 6)    NULL,
    [PercentMeasurementTypeID] INT                NULL,
    [PersonID]                 INT                NULL,
    [QuadCircumference]        DECIMAL (10, 6)    NULL,
    [UnitID]                   INT                NULL,
    [UpdatedAt]                DATETIMEOFFSET (7) NULL,
    [Version]                  VARCHAR (255)      NULL,
    [WaistCircumference]       DECIMAL (10, 6)    NULL,
    [WaterPercentage]          DECIMAL (10, 6)    NULL,
    [Weight]                   DECIMAL (10, 6)    NULL);

